### ISSUE TITLE
Create Pop-Up for Domain Match

### ISSUE THREAD

**Issue by guttermouth** [blunderboy/requestly#66]
Hey,

I was wondering if it is possible to modify requestly a little bit. I am looking for a solution which allows me to send/push an alert as a pop up when I visit a certain website. For example I go to www.amazon.com/Checkout then a pop up comes and asks me if I am sure that I typed in the correct address. Does anyone know if this is possible? Thanks for your help in advance.

**Comment by blunderboy** [comment]
@guttermouth Its difficult for me to understand the issue. Can you please explain a bit more ?

**Comment by lazyvab** [comment]
@blunderboy IIUC, requirement here is to execute some javascript on a page load.
Like example cited by @guttermouth, he wants an alert to be displayed on navigation to checkout page.
I think that should be possible.

**Comment by blunderboy** [comment]
@lazyvab @guttermouth I don't think we can support this use case in requestly. Here is an alternative way to do so:

1. Create a JS which shows alert/popup and host it somewhere say dropbox or even your local server
2. On checkkout page, try to find a script which can be redirected to your script without any impact on page like analytics script or similar.
3. Create a redirect rule where you redirect the script in step 2 with your script in step 1.
Make sure you do that only when your url matches checkout page otherwise you can see that popup on other pages as well.

I am closing this issue.
