### ISSUE TITLE
Update GitHub Release

### ISSUE THREAD

**Issue by n8henrie** [blunderboy/requestly#67]
New requestly user. Looks likea great extension that will scratch an itch I've had for a while!

I've just installed from source and am experiencing [a crippling bug](https://github.com/blunderboy/requestly/issues/41) with [the latest release](https://github.com/blunderboy/requestly/releases) available on GitHub (`v3.3.0`).

It looks like this may be fixed in `v3.3.4`, and the Chrome Store is serving `v3.3.8`. Can we get the GitHub tags / releases up to date for those of us wishing to install from source? For now I've just checked out `master`, which appears to be `v3.3.8`, but I'd prefer to be running a known stable release instead of just the latest source.

Also looks like `3.1.0` was released without a `v`.
```bash
$ git tag -l
3.1.0
v1.1.0
v1.2
v2.0
v2.1
v2.2
v2.2.1
v3.0
v3.3.0
```

Thanks again for the hard work and a great extension!

**Comment by blunderboy** [comment]
@n8henrie Thanks man for opening the issue. You may want to checkout out the build directory where I always keep [the stable builds](https://github.com/blunderboy/requestly/tree/master/build). But that's again you may not want this. 

In the beginning of every release I followed this practice to tag the branch but after sometime since I was the only collaborator and I had the builds folder I skipped this step in every release.

Now I know there are some users (like you) who wants to use tag, I'd do this right away from every release after wards.

Thanks for using it. Hope you make good use of it.

**Comment by blunderboy** [comment]
@n8henrie Done..You can get the latest tag now. Try

> git pull --all
> git tag -l

3.1.0
v1.1.0
v1.2
v2.0
v2.1
v2.2
v2.2.1
v3.0
v3.3.0
v3.3.8

> git checkout v3.3.8

Let me know if you need any help. I will take care of creating tags at every release now. Closing this issue.

**Comment by n8henrie** [comment]
Great! Thanks a ton! Was able to get things running properly with v3.3.4, and having it tagged is quite a bit nicer than `git log --grep=release` and checking out the commit.

**Comment by blunderboy** [comment]
Hi Nathan,

Agreed to your point. I assure you to tag my release commits from next
release onwards.
Let me know if you need some other help while using it or find some bug, I
would try my best to help you out.
