### ISSUE TITLE
Only works for typed URLs

### ISSUE THREAD

**Issue by eyalrin** [blunderboy/requestly#72]
Hi,

I am trying to use the extension in order to debug my web application. I am redirecting all rest calls (e.g., https://www.demo.com/rest/persons/ to http://localhost:8080/rest/persons/), but the only time I see that the call gets to my local machine is when I manually type the rest call in the address bar, but when requests are sent from the application (i.e. I see them being sent in chrome's network tab), I don't get them on my local machine. Is this a bug or just the normal limitation of the extension?

Thanks
Eyal

**Comment by blunderboy** [comment]
@eyalrin This is a pretty normal case and it should have worked with ease. I am using similar rules in my work almost everyday and I never encountered such an issue.

Can you provide a snapshot of your rule and the url which your application is making request to.
I just need to understand your rule is well built.

Quick steps to troubleshoot yourself:
1. Make sure you are not using *Equals* operator because in that case trailing "/" might matter in your case.
2. Try to use *Replace Rule* and replace http://www.demo.com to http://localhost:8080

Thanks for letting me know. If there is such bug, I'd try to fix this asap.

**Comment by eyalrin** [comment]
![screen shot](https://cloud.githubusercontent.com/assets/8133764/10552092/17255dec-745a-11e5-8c9a-d29e5efaa1a9.png)

Hi @blunderboy ,

I've attached a screenshot of the rules I configured. I've deleted the actual host I'm pointing to (it's a work related issue, so I don't want to disclose the company name), but I assure you that it is the right one.
One sample request from the application is going to https://xxx.xxx.xxx.com/rest/ads?max=30 and I wish it to go to http://localhost:8080/rest/ads?max=30 (please note that I moves from 'https' to 'http' as well as changed the host), but the request doesn't get to my local machine.

Thanks for the help!
Eyal

**Comment by blunderboy** [comment]
@eyalrin It could be a mixed content issue. Quick troubleshooting tips:

1. Go to Developer Tools, Network Tab and see if redirection is happening to localhost or not.
2. Go to Developer Tools and check if browser is saying "Blocked mixed content" warning. https://developer.mozilla.org/en/docs/Security/MixedContent

You will see a shield icon in top right of Chrome Address bar, click on it and enable mixed content.

Let me know  if this is a mixed content issue. Because when you type in Address Bar, you do not encounter mixed content issues. But when you try to load an HTTP request for script/ajax from https page browser blocks it.

I am most certain it should fix the issue.

**Comment by eyalrin** [comment]
Hi @blunderboy,

I looked at the developer tools and I think the problem is different - Before any of my application request, it send an OPTIONS request to the same URL. I need the OPTIONS request to not be redirected, and others (like GET, POST, etc) to get redirected - Can it be done?

Thanks!
Eyal

**Comment by blunderboy** [comment]
@eyalrin That means you are trying to redirect an XHR request with server authorization..Well technically it should be possible by hacking through the code of requestly but certainly that's not an option in UI. Requestly currently works on Url patterns and does not recognize Method of request.

You can give a try. Just clone the source code and write an additional line here 
https://github.com/blunderboy/requestly/blob/master/src/background/background.js#L175

    details.method.toLowerCase() !== 'options'

Load the extension from your disk by following these steps:
1. Go to chrome://extensions
2. Click load unpacked extension
3. Select the directory where you cloned the reaquestly code
4. Disable/Remove the requestly you downloaded from web/chrome store.

Hope it helps!!

**Comment by eyalrin** [comment]
Hi @blunderboy 

I'll try your suggestion as soon as possible - I'm a bit of backed up at work, I'll update on the result after.

Thanks!
Eyal

**Comment by blunderboy** [comment]
@eyalrin I do understand the priority of the work. Feel free to close the issue whenever you are done with your POC.

**Comment by eyalrin** [comment]
Hi @blunderboy,

I tried doing what you suggested and modified the line to:

        if (typeof rule.source !== 'undefined' && typeof rule.destination !== 'undefined' && details.method.toLowerCase() !== 'options') {

but when I open the extension, I get a black page with only the header and the footer shown and non of the oprions. When I look at the developer tools, I see that
chrome-extension://mdeimnligefehacakleaooakdaobapck/src/pages/templates.hbs.js
is not loaded (failed). Is that the reason for the blank page? and if so, where is the missing file?

Thanks!
Eyal

**Comment by blunderboy** [comment]
Arggh..Sorry my bad!! I forgot that we have to build the project before loading into chrome. You can try picking up latest build from here: https://github.com/blunderboy/requestly/tree/master/build

And extract it and make the modifications. Sorry about that!!

**Comment by eyalrin** [comment]
Hi @blunderboy,

I tried your suggestion and it didn't work - I think I should have changed Line 215 instead. When I did that, OPTIONS calls went to the actual server while other calls got to my local server. However, that didn't help my problem since I guess because the options was returned from one server and the GET (for example) got to a 2nd server, the call failed.

Nethertheless, I think I found a solution to my problem - when running chrome like so:
     open -a Google\ Chrome --args --disable-web-security

chrome doesn't uses OPTIONS calls and goes directly to the operation needed, which is registered on my local machine using Requestly. For now It seems to work :-)

Thanks for all the help!
Eyal

**Comment by blunderboy** [comment]
@eyalrin Right..I had this doubt in mind when I was suggesting the above approach. This means browsers ensure that preflight request and actual request should be on same origin. Thanks for this poc. 

Good to know you got to figure that out and its working for you. Closing this issue.
